### ISSUE TITLE
httpサーバーを建てずに表示する方法

### ISSUE THREAD

**Issue by 054478** [ics-creative/160304_threejs_save_point#1]
httpサーバーを建てずに、index.htmlを正しく表示させるにはどのようにすればいいのでしょうか？
（当方、プログラミング素人です。）

・①npm start→②http://localhost:8888/demo/では、問題なく表示されます。
・①npm run watch→②ブラウザで直接index.htmlを読み込んだのですが、表示がされません。

**Comment by ics-ikeda** [comment]
httpサーバーを立ち上げることなく、index.htmlを表示させることはできません。
npm startコマンドを利用いただければと思います。

※index.htmlをブラウザで開くと、`file://` プロトコルになります。WebGLでは`file://` プロトコルでは画像ファイルをテクスチャーとして読み込むことができません。そのため、実行時にランタイムエラーが発生します。
